name: Gnosis Chain
chain_id: 100
explorer_url: https://gnosis.blockscout.com
rpc_url: https://gnosis-rpc.publicnode.com
repos:
  - https://github.com/gnosischain/specs
abi_strategy:
  - explorer
  - repo
